export { default as MegaMenu } from './ui/mega-menu'
export { Navbar } from './Navbar'
export { HeroSection } from './HeroSection'
export { AboutSection } from './AboutSection'
export { ExperiencesSection } from './ExperiencesSection'
export { TestimonialsSection } from './TestimonialsSection'
export { InstagramSection } from './InstagramSection'
